openapi: 3.0.0
info:
  title: Drivers API
  version: 1.0.0
servers:
- description: Development server
  url: http://localhost:8082
paths:
  /api/drivers:
    post:
      description: Create a new driver
      operationId: createDriver
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDriverRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Driver"
          description: The request has succeeded and a new resource has been created
            as a result.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createDriver_422_response"
          description: Unprocessable Entity response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/drivers/{id}:
    delete:
      description: Delete driver
      operationId: deleteDriver
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "There is no content to send for this request, but the headers\
            \ may be useful. "
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Not Found response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-accepts:
      - application/json
    get:
      description: Get driver by ID
      operationId: getDriver
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Driver"
          description: The request has succeeded.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Not Found response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-accepts:
      - application/json
    put:
      description: Update driver
      operationId: updateDriver
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDriverRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Driver"
          description: The request has succeeded.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Not Found response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createDriver_422_response"
          description: Unprocessable Entity response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    CreateDriverRequest:
      description: Create driver request
      example:
        firstName: firstName
        lastName: lastName
        nationality: nationality
        dateOfBirth: 2000-01-23T04:56:07.000+00:00
      properties:
        firstName:
          maxLength: 50
          minLength: 1
          type: string
        lastName:
          maxLength: 50
          minLength: 1
          type: string
        nationality:
          maxLength: 3
          minLength: 2
          type: string
        dateOfBirth:
          format: date-time
          type: string
      required:
      - dateOfBirth
      - firstName
      - lastName
      - nationality
      type: object
    Driver:
      description: Formula 1 Driver
      example:
        firstName: firstName
        lastName: lastName
        metadata:
          createdAtTimestamp: 2000-01-23T04:56:07.000+00:00
          modifiedAtTimestamp: 2000-01-23T04:56:07.000+00:00
        nationality: nationality
        dateOfBirth: 2000-01-23T04:56:07.000+00:00
        id: id
        isActive: true
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        nationality:
          type: string
        dateOfBirth:
          format: date-time
          type: string
        isActive:
          type: boolean
        metadata:
          $ref: "#/components/schemas/EntityMetadata"
      required:
      - dateOfBirth
      - firstName
      - id
      - isActive
      - lastName
      - metadata
      - nationality
      type: object
    EntityMetadata:
      description: Entity metadata
      example:
        createdAtTimestamp: 2000-01-23T04:56:07.000+00:00
        modifiedAtTimestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        createdAtTimestamp:
          format: date-time
          type: string
        modifiedAtTimestamp:
          format: date-time
          type: string
      required:
      - createdAtTimestamp
      - modifiedAtTimestamp
      type: object
    Error:
      description: Error response model
      example:
        code: code
        message: message
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          format: date-time
          type: string
      required:
      - code
      - message
      - timestamp
      type: object
    UpdateDriverRequest:
      description: Update driver request
      example:
        firstName: firstName
        lastName: lastName
        nationality: nationality
        dateOfBirth: 2000-01-23T04:56:07.000+00:00
        isActive: true
      properties:
        firstName:
          maxLength: 50
          minLength: 1
          type: string
        lastName:
          maxLength: 50
          minLength: 1
          type: string
        nationality:
          maxLength: 3
          minLength: 2
          type: string
        dateOfBirth:
          format: date-time
          type: string
        isActive:
          type: boolean
      type: object
    ValidationError:
      description: Validation error details
      example:
        code: code
        field: field
        message: message
        rejectedValue: rejectedValue
      properties:
        code:
          type: string
        message:
          type: string
        field:
          type: string
        rejectedValue:
          type: string
      required:
      - code
      - field
      - message
      type: object
    createDriver_422_response:
      example:
        code: code
        message: message
        errors:
        - code: code
          field: field
          message: message
          rejectedValue: rejectedValue
        - code: code
          field: field
          message: message
          rejectedValue: rejectedValue
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
        timestamp:
          format: date-time
          type: string
      required:
      - code
      - errors
      - message
      - timestamp
      type: object

