openapi: 3.0.0
info:
  title: Seasons API
  version: 1.0.0
servers:
- description: Development server
  url: http://localhost:8086
paths:
  /api/seasons:
    post:
      description: Create a new season
      operationId: createSeason
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSeasonRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Season"
          description: The request has succeeded and a new resource has been created
            as a result.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createSeason_422_response"
          description: Unprocessable Entity response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/seasons/{id}:
    delete:
      description: Delete season
      operationId: deleteSeason
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "There is no content to send for this request, but the headers\
            \ may be useful. "
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Not Found response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-accepts:
      - application/json
    get:
      description: Get season by ID
      operationId: getSeason
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Season"
          description: The request has succeeded.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Not Found response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-accepts:
      - application/json
    put:
      description: Update season
      operationId: updateSeason
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSeasonRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Season"
          description: The request has succeeded.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request response
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Not Found response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createSeason_422_response"
          description: Unprocessable Entity response
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error response
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    CreateSeasonRequest:
      description: Create season request
      example:
        year: 1956
        endDate: 2000-01-23T04:56:07.000+00:00
        name: name
        startDate: 2000-01-23T04:56:07.000+00:00
      properties:
        year:
          format: int32
          maximum: 2030
          minimum: 1950
          type: integer
        name:
          maxLength: 100
          minLength: 1
          type: string
        startDate:
          format: date-time
          type: string
        endDate:
          format: date-time
          type: string
      required:
      - endDate
      - name
      - startDate
      - year
      type: object
    EntityMetadata:
      description: Entity metadata
      example:
        createdAtTimestamp: 2000-01-23T04:56:07.000+00:00
        modifiedAtTimestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        createdAtTimestamp:
          format: date-time
          type: string
        modifiedAtTimestamp:
          format: date-time
          type: string
      required:
      - createdAtTimestamp
      - modifiedAtTimestamp
      type: object
    Error:
      description: Error response model
      example:
        code: code
        message: message
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          format: date-time
          type: string
      required:
      - code
      - message
      - timestamp
      type: object
    Season:
      description: Formula 1 Season
      example:
        metadata:
          createdAtTimestamp: 2000-01-23T04:56:07.000+00:00
          modifiedAtTimestamp: 2000-01-23T04:56:07.000+00:00
        year: 0
        endDate: 2000-01-23T04:56:07.000+00:00
        name: name
        id: id
        isActive: true
        startDate: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        year:
          format: int32
          type: integer
        name:
          type: string
        startDate:
          format: date-time
          type: string
        endDate:
          format: date-time
          type: string
        isActive:
          type: boolean
        metadata:
          $ref: "#/components/schemas/EntityMetadata"
      required:
      - endDate
      - id
      - isActive
      - metadata
      - name
      - startDate
      - year
      type: object
    UpdateSeasonRequest:
      description: Update season request
      example:
        year: 1956
        endDate: 2000-01-23T04:56:07.000+00:00
        name: name
        isActive: true
        startDate: 2000-01-23T04:56:07.000+00:00
      properties:
        year:
          format: int32
          maximum: 2030
          minimum: 1950
          type: integer
        name:
          maxLength: 100
          minLength: 1
          type: string
        startDate:
          format: date-time
          type: string
        endDate:
          format: date-time
          type: string
        isActive:
          type: boolean
      type: object
    ValidationError:
      description: Validation error details
      example:
        code: code
        field: field
        message: message
        rejectedValue: rejectedValue
      properties:
        code:
          type: string
        message:
          type: string
        field:
          type: string
        rejectedValue:
          type: string
      required:
      - code
      - field
      - message
      type: object
    createSeason_422_response:
      example:
        code: code
        message: message
        errors:
        - code: code
          field: field
          message: message
          rejectedValue: rejectedValue
        - code: code
          field: field
          message: message
          rejectedValue: rejectedValue
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
        timestamp:
          format: date-time
          type: string
      required:
      - code
      - errors
      - message
      - timestamp
      type: object

